### ISSUE TITLE
Enable HTML formatting in linguistic analysis pop-up

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/morphodict#1024]
For presenting potentially complex lexical information that is shown in the linguistic pop-up, we'd need the ability to format, if simply, that information, cf.

<img width="967" alt="image" src="https://user-images.githubusercontent.com/15003407/143568087-572a7649-c1c9-49cc-9b23-723f02322de8.png">

For instance, we might want to present a HTML table with principal parts and associated information as follows:

| **Aspect**                         | **Theme**           | **TAMA** |
| -----                                  | -----                     | :-:     |
| Imperfective                      | nà=gu_di.tłod       | 0i             |
|  Perfective                         | nà=gu_di.tłòt        | sii            | 
|  Progressive                       | nà=gu_di.tłíł         | yii            | 
|  Imperfective + Repetitive | nàná=gu_di.tłiizh | 0i             | 
|  Imperfective + Repetitive | nìná=gu_di.tłiizh  | 0i             |

**Comment by aarppe** [comment]
Of course, the row and column labels could be opened for relabeling!

**Comment by aarppe** [comment]
The following is the format this could have in HTML:

<table colspan=3>
<tr><td>Aspect</td><td>Theme</td><td>TAMA</td></tr>
<tr><td>Imperfective</td><td>nà=gu_di.tłod</td><td>0i</td></tr>
<tr><td>Perfective</td><td>nà=gu_di.tłòt</td><td>sii</td></tr>
<tr><td>Progressive</td><td>nà=gu_di.tłíł</td><td>yii</td></tr>
<tr><td>Imperfective + Repetitive</td><td>nàná=gu_di.tłiizh</td><td>0i-IPFV</td></tr> 
<tr><td>Imperfective + Repetitive</td><td>nìná=gu_di.tłiizh</td><td>0i</td></tr> 
</table>

**Comment by aarppe** [comment]
As a further note, the above table (using linguistic labels) could be relabeled according to any of the other two options, i.e. with plain English or (plain) nêhiyawêwin labeling, e.g.

| **Aspect**                             | **Theme**           | **Chunk** |
| -----                                      | -----                     | :-:              |
| Non-past                               | nà=gu_di.tłod       | 0i              |
| Past                                        | nà=gu_di.tłòt       | sii              | 
| Ongoing                                 | nà=gu_di.tłíł         | yii              | 
| Non-past + Again and again | nàná=gu_di.tłiizh | 0i               | 
| Past + Again and again         | nìná=gu_di.tłiizh  | 0i               |

**Comment by nienna73** [comment]
I know the word and the info in the table don't correspond, but how is this looking?

We need to come up with a name for this information. It's currently under "linguistInfo" as "analysis" but that doesn't seem quite right. 

![Screen Shot 2022-03-24 at 11 24 39 AM](https://user-images.githubusercontent.com/28357720/159974748-27d5639e-33e6-4dad-9a87-0044bb5f6737.png)

**Comment by aarppe** [comment]
That looks like what I was expecting.

I think this does resurrect our discussion concerning the `LinguistInfo` field, and since it's contents are coming from the lexical database, it would make more sense to call it `LexicalInfo` of `LexicographicalInfo` instead.

One could think of the table being such lexical information, but there could be other types, e.g. concerning derivational morphological breakdown, etymology, etc., so one would want to have a distinct name. One option would be to call that `PrincipalParts` (which is what the content approximately is), but that pertains to a particular morphological tradition ([https://link.springer.com/content/pdf/10.1007/s11525-007-9115-9.pdf](https://link.springer.com/content/pdf/10.1007/s11525-007-9115-9.pdf)) that might not always apply - but for now that might be good enough, though I'll try to consult some others if there could be a better term.

**Comment by nienna73** [comment]
For right now, it relabels anything it can, and if that item isn't in the relabelling scheme, it leaves it as is. This assumes the specific and exact table definition above as there is a regular expression that looks for those tags. We can chat about this during our meeting tomorrow.

**Comment by aarppe** [comment]
Ok - I'll add what I can concerning the codes in the paradigm parts, primarily for Tsuut'ina.
