### ISSUE TITLE
Rename arpeng.altlab.dev as nihiitono.altlab.dev

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/morphodict#1051]
Having confirmed this with Andy Cowell, the Arapaho equivalent of **_words_** is **_nihíitono_**, so we can rename the Arapaho morphodict instance (without accent marking) as: `nihiitono.altlab.dev`

**Comment by aarppe** [comment]
@nienna73 Just got this sorted out and confirmed.

**Comment by nienna73** [comment]
Solved in #1052

**Comment by aarppe** [comment]
This is excellent - though I noticed we need to rename the caption under the logo as well: 
<img width="191" alt="image" src="https://user-images.githubusercontent.com/15003407/153313307-3b13b59b-a0b2-4226-8a37-136d679fd3dd.png">

**Comment by nienna73** [comment]
Good catch, that's solved now.

**Comment by aarppe** [comment]
And we need to inform Andy Cowell about this.
