### ISSUE TITLE
Morpheme boundaries missing when cell has multiple forms

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/morphodict#1071]
For instance in the following case, when the cell has two possible wordforms, the morpheme boundaries do not get shown (even though the FST does generate them).

<img width="387" alt="image" src="https://user-images.githubusercontent.com/15003407/161188617-c088bf58-0c5e-4204-b72c-88fab013bc51.png">

```
hfst-lookup -q src/crk-strict-generator-with-morpheme-boundaries-giellaltbuild.hfst
wâpahtam+V+TI+Ind+12Pl
wâpahtam+V+TI+Ind+12Pl	ki<wâpahtê>naw	0.000000
wâpahtam+V+TI+Ind+12Pl	ki<wâpahtê>nânaw	0.000000
```

**Comment by nienna73** [comment]
I found the cause of this issue. When we give the morpheme boundary FST an analysis that returns two results, we have no way of knowing which result needs to be returned or has already been returned. So the first time it receives the analysis `wâpahtam+V+TI+Ind+12Pl`, it should return `ki<wâpahtê>naw`, and the second time it should return `ki<wâpahtê>nânaw`. We have no way of knowing if this is the first, second, fifth, etc. time we're receiving this analysis, though.

I'm working on a way around this issue.
