### ISSUE TITLE
legend page down

### ISSUE THREAD

**Issue by mosaicthej** [UAlbertaALTLab/morphodict#1193]
https://itwewina.altlab.app/legend

Gives 500 error.

Not sure if this is the right repo for this issue.

**Comment by fbanados** [comment]
This is the right repo! sorry I hadn't had the time to see this earlier.  Will report here as I make progress on the issue.

**Comment by fbanados** [comment]
Bug was a consequence of the changes for #1181 , updating the legend template to point to the right entry

**Comment by fbanados** [comment]
Update to legend code and testing has been deployed, and the legend page should be working again.  Thanks for this bug report!
