### ISSUE TITLE
Cite WordNet in the English-to-Cree search results

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/morphodict#1203]
_Originally posted by @aarppe in https://github.com/UAlbertaALTLab/morphodict/issues/1138#issuecomment-2516589589_

- [x] Add WordNet as the source for the English sense definitions, with the acronym WN.

When we're using WordNet, we need to properly cite it, referring to [https://wordnet.princeton.edu/citing-wordnet](https://wordnet.princeton.edu/citing-wordnet), shortened to something like the following:

_WordNet: A Lexical Database for English, by George A. Miller, 1995, and WordNet: An Electronic Lexical Database, by Christiane Fellbaum, editor, 2001._

We can have the full references on our [About](https://itwewina.altlab.app/about) page:

* George A. Miller (1995). WordNet: A Lexical Database for English. Communications of the ACM Vol. 38, No. 11: 39-41.

* Christiane Fellbaum (1998, ed.) WordNet: An Electronic Lexical Database. Cambridge, MA: MIT Press.

... as well as refer to their Copyright, probably also on our [About](https://itwewina.altlab.app/about), available here:

[https://wordnet.princeton.edu/license-and-commercial-use](https://wordnet.princeton.edu/license-and-commercial-use)

**Comment by fbanados** [comment]
Is the current approach deployed in dev sufficient?  We can close this issue if so.

**Comment by aarppe** [comment]
Yes, though you might leave the "computational" out of the description on the About page (as the WN classifications were manually assigned).

And I think we ought to add a reference or few to our own work here, namely: [Dacanay, Daniel, Atticus G. Harrigan & Antti Arppe (2021, March 2](doi:https://doi.org/10.33011/computel.v1i.971)). Computational Analysis versus Human Intuition: A Critical Comparison of Vector Semantics with Manual Semantic Classification in the Context of Plains Cree(https://altlab.ualberta.ca/wp-content/uploads/2021/10/2021.computel-1.5.pdf). Proceedings of the 4th Workshop on Computational Methods for Endangered Languages, 1, 33-43. doi:https://doi.org/10.33011/computel.v1i.971

**Comment by fbanados** [comment]
Should the new reference go with the others in "About" or also on the popup?

**Comment by aarppe** [comment]
The references would just go to the About page. We take the definitions and synonym sets directly from WN, without any editing by ourselves - it is only their application to the English definitions of the various sources which is our own new contributions.

**Comment by aarppe** [comment]
Something like: "The application of WordNet (and RapidWords) semantic classifications to the English definitions of the Cree dictionary content is described in Dacanay, Harrigan & Arppe (2021) and Dacanay (2022), among others."

**Comment by fbanados** [comment]
I think this should be done now (and deployed in .dev)
