### ISSUE TITLE
Discontinue AOT paradigm generation in favour of JIT paradigm generation

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/morphodict#389]
AOT: ahead-of-time
JIT: just-in-time

Currently, whenever the FST is updated, or the dictionary contents are updated, we need to re-generate ALL of the inflections used in every paradigm of all the lemmas that the FST can inflect. This has the advantage that the initial page load for EVERYBODY is _super_ speedy, but has one major downside: we need to rebuild the database anytime the FST changes, or the dictionary content changes.

Currently, this is a semi-automated process, but it still takes time. So all the inflections are generated **ahead-of-time**.

**Theoretical background**: the generated inflection database is a _accidental_ state, rather than _essential_ state [[Brooks, 1995]](http://worrydream.com/refs/Brooks-NoSilverBullet.pdf). We want to reduce accidental state — i.e., caches, state we can generate with code from existing data, — and rely on essential state — i.e., the dictionary and FST. Right now, we're treating the inflections as if they are essential state, despite the fact that it is generated.

**Proposal**: instead of generating all inflections all at once, we generate _and cache_ inflections as they are needed — just-in-time. Generating inflections can also happen in a background process whenever the FST changes and invalidates the current inflection cache. It's important to remember [the two hardest problems in computer science](https://martinfowler.com/bliki/TwoHardThings.html).

What I haven't thought of yet is how this will interact with fuzzy search, and other search mechanisms that lookup all wordforms directly.

**Comment by aarppe** [comment]
When the linguists (lately me) update the FST, they have a relatively good idea about what section of the paradigms are impacted. For instance, much of the work in the last few months has concerned fixing AI and TA verbs, and not really touching nouns, pronouns, or particles at all. The same applies to the most recent changes, which have turned tense from a suffixal feature to a preverb one - this, too, should have had no impact on nouns and other non-verb word-classes. Also, there's been one substantial expansion of the underlying database, which would have required in practice an update of all the paradigms. 

Could one consider explicitly re-generating the paradigms only for inflectional subclasses known to have changed? The rest could be generated gradually in a more fuzzy manner.

In principle, when we get various functionalities fully implemented, we wouldn't be generating new full paradigms every day, but let us say once a month, with a new batch arriving from AEW or the MD validation work.

Anyhow, this could benefit from some general strategizing and discussion.

**Comment by Madoshakalaka** [comment]
Some essential parts needs us to build stuff aot still: affix search and fuzzy search requires ALL inflections beforehand. Maybe just in memory.

**Comment by aarppe** [comment]
@eddieantonio @andrewdotn Is this a relevant issue anymore?

**Comment by eddieantonio** [comment]
We still produce all inflections ahead-of-time. There was a brief window of time when it was not necessary at all, but with English phrase translation, ahead-of-time seems to be the best option for now. What do you think, @andrewdotn?

**Comment by eddieantonio** [comment]
FYI, here is the code that does the AOT paradigm inflection generation, in the `importjsondict` command:

https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/blob/7c4ffc1d5e73802dfcf790f245e28fa9617bb959/src/morphodict/lexicon/management/commands/importjsondict.py#L134-L151

**Comment by andrewdotn** [comment]
My intent is to update this when making the import incremental:
  - We will instantiate wordforms for which auto-translation can produce definitions, so that there is a database entity to attach the auto-translated definition to
  - We will not spend a bunch of import time creating database entries that take up a bunch of space and are never used.

**Comment by andrewdotn** [comment]
The new import process only instantiates wordforms for which a definition exists. That may be an auto-translated definition.

Someone may want to double-check if this has truly broken affix search as a comment above indicates is a possibility.
