### ISSUE TITLE
Show morphological breakdown structure (inflectional morpheme boundaries first)

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/morphodict#397]
EDIT (29.2.2022): removed exception for morpheme boundaries in conjunction with hyphens `-`.

Subtasks (added July 20):
- [x] 1. implement marking of inflectional morpheme boundaries in FST output (now indicated with `<` and `>` marks for inflectional boundaries, and `/` for derivational boundaries): `nôhkom+N+A+D+Px1Pl+Pl` --> `ni4<ohkom>i2nân>ak` --> `n<ôhkom>inân>ak`
- [x] 2. implement back-end interpretation and representation of morpheme boundaries, looking up FST morpheme boundaries (which could be done upon importation of dictionary content and the dynamic generation of the paradigm content) and communicating that appropriately to the front-end.
- [x] 3. implement front-end representation of morpheme boundaries (e.g. with `middle-dot`). For now, this could even be implemented as **not** showing anything, until we decide how to best represent morpheme boundaries.

Since our FST already outputs morpheme boundaries (primarily inflectional ones), there would be many circumstance when it would be advantageous to show those, in the standardized version of the search string, as well as in the generated inflectional paradigms:

One way to achieve this would be to represent the inflectional morpheme boundaries that the FST outputs as `<` and `>` with a middle-dot `·`, something like the following:

![image](https://user-images.githubusercontent.com/15003407/80674781-0e5a7180-8a70-11ea-8e70-45b49f65d0bb.png)

Ideally, that middle dot (or any other character) would not be copyable, so when one paints and copies any wordform, one only gets the actual characters.

Alternatives could be using different colors or shading to differentiate the morphemes, or some visual animation effects such as slight magnification when hovering over individual morphemes. On the other hand, having the morpheme boundaries immediately but non-intrusively available might be the simpler solution - or one might have the morpheme-boundary-output option as a **output setting that can be triggered similar to the selection of orthography**. Also, we might want to keep magnification or pop-ups till later for giving the plain-language definition of each morpheme. Finally, one might provide such a breakdown explicitly when going after the full paradigms.

![image](https://user-images.githubusercontent.com/15003407/80674800-1e725100-8a70-11ea-9f6c-23a01942c5cc.png)

First, we could implement this for inflectional morpheme boundaries, and later on for derivational boundaries as well.

**Comment by aarppe** [comment]
And here's a draft visualization for providing further information about inflectional morphemes as pop-ups:

![image](https://user-images.githubusercontent.com/15003407/80189398-d6ff4700-85cf-11ea-8d38-0986f36a1363.png)

**Comment by aarppe** [comment]
@kobexamoh Note - I updated the mock-up vizualizations above.
The first (i) refers to the linguistic breakdown of the inflected word form.
The second (i) refers to inflectional subcategory information for the dictionary entry.

These two are different types of information - keeping them separate clarifies things, as well as moving the (Verb/Noun - ...) information next to the dictionary entry rather than the word form.

**Comment by aarppe** [comment]
As discussed in our meeting this last week of July, we might want to have multiple forms of information available for each paradigm layout cell. For instance, the following:

```
V+TA+Ind+1Sg+2SgO:	kiwâpamitin : (1) surface word-form without morpheme boundaries
			ki<wâpam>iti>n : (2) surface word-form with morpheme boundaries
			kit2<wâpam>i2ti >n : (3) underlying word-form with original morphemes and boundaries
			I see me, I witness me : (4) generated English translation of cell word-form
			(5) human recording
			(6) generated robot recording
```

**Comment by nienna73** [comment]
I found a demo of how this currently works, here's how it looks:
![Screen Shot 2022-03-29 at 11 44 12 AM](https://user-images.githubusercontent.com/28357720/160673147-e83134c1-d68c-4941-8e90-758140e510bf.png)

Is this more or less the expected behaviour on the main page?

Here's another with multiple morphemes:
![Screen Shot 2022-03-29 at 11 45 40 AM](https://user-images.githubusercontent.com/28357720/160673296-c2217ebc-febd-48f9-a44d-55965f6d3af7.png)


If this is visually what we're going for, then I can work on adding the option to see morpheme boundaries to the settings page, as well as showing morpheme boundaries within paradigm layouts.

**Comment by aarppe** [comment]
Yes, I think we thought that the middle-dot would be a good way to indicate the morpheme boundaries. I think we might want to show the middle-dot also in conjunction with hyphens, to indicate that there's a morpheme boundary there as well, i.e. `ni·kî-·wâpam·âw·ak` (I realize I'm changing my mind from what I had written earlier above). Further inspirations can be found in #505.

**Comment by nienna73** [comment]
I added morpheme boundaries to the settings:

![Screen Shot 2022-03-29 at 2 11 37 PM](https://user-images.githubusercontent.com/28357720/160698924-6aeb8c8b-ff29-41d8-a47c-7bd6b9e4f90e.png)

This is what they look like in the paradigm:

![Screen Shot 2022-03-29 at 2 12 08 PM](https://user-images.githubusercontent.com/28357720/160698988-389f657b-7231-48bf-9451-c4cdf693f133.png)


The one place I can't seem to get them to show up is here:
![Screen Shot 2022-03-29 at 2 12 15 PM](https://user-images.githubusercontent.com/28357720/160699024-97cd52e4-2b7c-4aa3-b2c6-92962463c10c.png)

**Comment by aarppe** [comment]
Great progress! Looks good! The reason for the latter case is that the word-form comes out of the lexical database, which is statically defined and doesn't contain morpheme boundaries. We'd have to add those as a separate computational step -- generally not too difficult, but I would not be surprised by edge cases that cause the most head aches.

**Comment by aarppe** [comment]
Next step of showing information on individual morphemes moved over to #1093, and for individual word-forms in paradigm cells to #1094.
