### ISSUE TITLE
Use <ic> instead of <lc> in the source XML files.

### ISSUE THREAD

**Issue by Madoshakalaka** [UAlbertaALTLab/morphodict#454]
@aarppe 

Current we are having `<lc>NA-4w</lc>` in the source XML file. While we are using the term "inflectional category" in the repository.

Can we use `<ic>` instead in the source file?

**Comment by aarppe** [comment]
The `<lc>` field (legacy term) in `crkeng.xml` tells us _inflectional category_.

**Comment by aarppe** [comment]
Since we no longer use XML for our dictionary DB, this issue is no longer active nor relevant.
