### ISSUE TITLE
morphodict: Refactor into two apps: a language-specific app and a language-agnostic app

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/morphodict#463]
- a Django application for creating a language-agnostic morphological dictionary. I'll call this `morphodict`: this will manage and maintain the `Wordform`, `DictionarySource`, and related models.
 - a Django application containing language-specific information, such as an "about" page, "contact us", etc. for now, I'll call this `itwewina`.
 - the Django project is configured in `settings.py` which configures the `morphodict` app with the module paths to the morphological analyzer/generator, paths to layouts, paths to the relabelling file, module path to orthographic transformations, etc.

The idea is to extract a framework for creating morphologically-intelligent dictionaries, including itwīwina, Gunana, and many, many more!

@Madoshakalaka, what are your ideas on this?

**Comment by Madoshakalaka** [comment]
Look good to me!

**Comment by aarppe** [comment]
@eddieantonio Is this the same as a refactoring plan (for Matt)?

Where would the following items belong? Under the language-specific app?
* paradigm and their layout specifications?
* relabeling schemes?

**Comment by eddieantonio** [comment]
> @eddieantonio Is this the same as a refactoring plan (for Matt)?

Yes.

> Where would the following items belong? Under the language-specific app?
> 
> * paradigm and their layout specifications?
> * relabeling schemes?

So it would be split: there's the language-specific parts like `crk.altlabel.tsv` that would be in the `itwewina` app; and we would have generalized code for dealing with any relabelling in the `morphodict` app. Same with the paradigm layouts: there would be generalized code in `morphodict` that can interpret any layout; and there would be the actual layouts in `itwewina`.

Note that "app" in this context is a what Django calls an "application" and not what we typically mean by "app"; it's essentially just a bit of Django code that can be reused across many different websites. e.g., we'd want Gúnahà to used the `morphodict` app and provide its own customizations; itwîwina would also use `morphodict`.

**Comment by aarppe** [comment]
Great! This is what I presumed.

Happy Midsummer Day!

**Comment by aarppe** [comment]
@andrewdotn I'd presume that the recent morphodict developments in effect cover this.

**Comment by andrewdotn** [comment]
More work could be definitely be done here, but it seems to be of fairly low value right now, given that we can stand up new dictionaries in a few hours. In light of that, I would call the refactoring a success.

The plan for how to eventually get rid of the `CreeDictionary` folder entirely is described here:
https://morphodict.readthedocs.io/en/latest/directory-structure.html Technically the generalization is not ‘done’ until that folder is completely gone, but my focus has definitely been on getting functionality working for new languages more than on changing what the folders are called.
