### ISSUE TITLE
What FSTs are we using for morphological analysis wrt morpheme boundaries?

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/morphodict#535]
It appears that the current crk source code for morphophonology, `src/fst/phonology.xfscript`, in `giellalt/lang-crk` does not actually remove any morpheme boundaries.

This means that the morpheme boundaries should remain on both the analysis and generation side (when e.g. the FST is compiled using our own compilation script), unless the morpheme boundaries are explicitly removed elsewhere (by e.g. the GiellaLT compilation scripts, most likely using the filter: `src/filters/remove-infl_boundary-marks.hfst`).

Crucially, our own compilation script should keep the morpheme boundaries and not remove them - we don't want to require them on the analysis side, but we do need them on the generation side.

@eddieantonio So, we need to check what FSTs do we use in itwêwina?

**Comment by eddieantonio** [comment]
We are using these FSTs: https://github.com/UAlbertaALTLab/plains-cree-fsts/releases/tag/20200330

We are **NOT** using the FSTs from Giella right now

**Comment by aarppe** [comment]
Ok - I checked the compilation script, and since we're using `phonology.xfscript` now we'd have to change that. With the current version of `phonology.xfscript` always results in FSTs with morpheme boundaries, which are in GiellaLT stripped with a specific transcriptor, that we'd have to add to our own scripts.

**Comment by eddieantonio** [comment]
Okay! So here's my plan:

 - [ ] we compile the FSTs in Giella
 - [ ] we load the generator FST into itwewina, however, since much of itwêwina is unaware of morpheme boundaries, we include it twice: once normally (with boundaries) and then in Python, we create a fake FST that delegates to the real FST (with morpheme boundaries); however, it simply parses the output, removes morpheme boundaries, and passes it back to the rest of itwêwina as if nothing ever happened
 - [ ] _then_ we make itwêwina aware of morpheme boundaries, slowly
 - [ ] it would also be good for Giella to automatically build the requisite FSTs
 - [ ] ...and issue a pull request to itwêwina when the latest FST is ready :)

**Comment by aarppe** [comment]
I had been thinking that the explicit-boundary generator FST could be wrapped in python so that the boundaries (of which crk has two `<` and `>`, but might have three, i.e. `/ `as well) are either shown or stripped, based on user preference. Is that what you are effectively suggesting?

As far as I could imagine, itwêwina would need to call the generator FST in two places: a) when it generates the standardized form of the Cree search string; and b) when it generates the contents of the cells in the paradigms. Is this the case, or is the generator invoked in more places? Depending of whether the user has toggled the boundaries to be shown or not, the output of the generating FST could then be filtered accordingly. I suppose we could even internally interpret the results of the generated word form as a sequence of morphemes, prefixes, stem (which could be divided into initials, medials, and finals), and suffixes, and these morphemes could be linked to a morpheme dictionary (of which a version exists by Mühlbauer and Cook and which we have).

As for Giella, it should allow for boundary-explicit FSTs with the option `./configure --enable-morpher,` but that doesn't work yet, of course. I can revise our own compilation code so that the FST generator produces morpheme boundaries. Automatic building of FSTs in conjunction with Giella is done by Apertium (I just don't know the exact details of that).

**Comment by aarppe** [comment]
Based on what I discussed with Sjur, one could add to `./configure` and option `--with-boundaries` that would create a normative generating FST showing morpheme boundaries in its output. When that would actually be realized is another question (and perhaps something for Eddie and Sjur to co-ordinate).

In the meantime, the quick.mk make file already generates the FST we need, in:

`../giellalt/lang-crk/src/crk-normative-generator-with-morpheme-boundaries.hfst
`
```
hfst-lookup -q src/crk-normative-generator-with-morpheme-boundaries.hfst
maskwa+N+A+Der/Dim+N+A+Px1Pl+Loc
maskwa+N+A+Der/Dim+N+A+Px1Pl+Loc	ni<mask>om>is>inâhk	0.000000

PV/ki+RdplW+wâpamêw+V+TA+Ind+1Sg+3SgO
PV/ki+RdplW+wâpamêw+V+TA+Ind+1Sg+3SgO	ni<kî-<wa-<wâpam>âw	0.000000
```
So we should already have the FST ingredients needed for indicating morpheme boundaries. We just need to interpret the results properly as part of our paradigm presentation (and search string standardization).
