### ISSUE TITLE
What's the deal with tipêńimâkan?

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/morphodict#551]
https://sapir.artsrn.ualberta.ca/cree-dictionary/word/tip%C3%AA%C5%84im%C3%A2kan/

Is this a Y-dialect word? If so, shouldn't the <ń> be converted to an <n>?

**Comment by katieschmirler** [comment]
Appears to be a borrowing?

**Comment by katieschmirler** [comment]
![Uploading 20201007_134307.jpg…]()

**Comment by eddieantonio** [comment]
> Picture doesn't want to upload, but it's marked as Swampy Cree in the dictionary entry

Should it be in Plains Cree itwêwina?

**Comment by katieschmirler** [comment]
> > Picture doesn't want to upload, but it's marked as Swampy Cree in the dictionary entry
> 
> Should it be in Plains Cree itwêwina?

You'd have to ask Arok. Since he included it, I'd assume it's a Swampy Cree word being used in its n form by Plains Cree speakers. If so, of course it should be included.

**Comment by eddieantonio** [comment]
> > > Picture doesn't want to upload, but it's marked as Swampy Cree in the dictionary entry
> > 
> > 
> > Should it be in Plains Cree itwêwina?
> 
> You'd have to ask Arok. Since he included it, I'd assume it's a Swampy Cree word being used in its n form by Plains Cree speakers. If so, of course it should be included.

With the <ń> be converted to an \<n\>, right?

**Comment by eddieantonio** [comment]
@aarppe, could you please ask Arok about this?

**Comment by aarppe** [comment]
The <ń> indicates that it's a Swampy/n-dialect word (originally, I believe) which has a dialectal -y- that is manifested as -n-. I'll have to ask Arok about whether it's a legitimate Plains Cree word.

**Comment by eddieantonio** [comment]
@aarppe you contacted Arok, correct? I believe this need to be changed to \<y\> instead of the \<ń\> in the database. Where exactly will this need to be changed? Could you please change it?
