### ISSUE TITLE
Specifications of general expectations for English itwêwina search (compounds and phrases)

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/morphodict#589]
In addition to the single-word/term queries specified in #543, we would also like _itwêwina_ to address the following user queries, when searching with multiple English words:

1. What is the Cree word for some English word (which may be a compound word)
   a. What is the Cree word for _stove pipe_?
   b. As a result, you'd expect: _okohtaskwahikan_, _kohtaskwahikan_, _ospwâkanihkân_, _oskicîhkân_ and _ospwâkanêhikan_
   c. Challenge: how to present the results in the order of most relevance?

2. What is the Cree word for some concept in English, expressed with multiple words
    a. What is the Cree word for _work(ing) together_?
    b. As a result, you'd expect the following results below - these were extracted as an intersection of _work_ and _together_. We might consider stemming these key terms, so that _works_, _working_ or _worked_ and _together_ result in the same match.

| Cree dictionary entry (CW) | English translation |
| --- | --- |
| mâmawatoskêwak | they work together as a group, they work as a team |
| mâmawi-atoskêwak |        they work all together |
| mâmawi-isîhcikêwak |      they work together, they participate in a cultural activity together |
| mâmawi-isîhcikêwin |     working together, participating in a cultural activity together |
mâmawohkamâtowak |       they do things together, they cooperate; they work (at it/him) together as a group |
mâmawohkamwak |  they work together on s.t. as a group ; they engage in a joint effort |
mihcêtohkamawêwak |      they work together to help s.o. |
mihcêtohkamâtowak |      they work together to help one another |
mihcêtohkamwak | they work together on s.t. |
nîsôhkamâtowak | they work together at (it/him) as two |
wîtapimêw |      s/he sits with s.o., s/he sits beside s.o., s/he stays with s.o., s/he is present with s.o.; s/he works together with s.o.; s/he sits by s.o. (in marriage) |
wîtatoskêmêw |   s/he works together with s.o., s/he has s.o. as his/her fellow worker

3. What is the Cree word for some inflected English phrase
   a. What is the Cree word for _I saw you_ or _I am going to see you_, or _I want to see you_?
      * The English phrase contains **subject pronouns** such as _I, you, he, she, it, we, they_, **object pronouns** such as _me, you, him, her, it, us, them_, or **reflexives** such as _myself, yourself, himself, herself, itself, ourselves, yourselves, themselves_.
      * The English phrases contains inflected verb phrases such as _saw_, _am going to see_, _want to see_.

   b. Expected results: _kikî-wâpamatin_ or _kika-wâpamitin_ or _kiwî-wâpamitin_.
   c. Solutions:

      + The search could use these function words (indicating subject, object, tense) as key words and search among generated inflected English phrases <-- this requires that these English phrases are in fact generated.
      + Alternatively, the search phrase could be parsed for subject, object and tense, and the remainder used for regular keyword search as in 2, and then the found Cree result would be rendered in the appropriate inflected form.

   d. Challenges:

      + Distinguishing among the argument classes (AI, TI, TA), or ordering such results --> Solution(s): showing AI and TI first, and then TA, if object pronouns are absent in the search. If object pronouns are present in the search, then show only TA forms (and perhaps after them, TIs).

**Comment by aarppe** [comment]
The most important remaining element is presented in #524.

**Comment by nienna73** [comment]
This issue is better described in #524.
