### ISSUE TITLE
Explore combination of corpus-frequency and lemma-character length in ranking

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/morphodict#644]
Since we do have corpus-based lemma frequencies, those could be used to rank the crk results in an English query. Indeed, this is already used, but the results are suboptimal as there is no part-of-speech matching of the search terms and crk lemmas.

It would seem that matching English verbs with Cree verbs (of any conjugation class type), English nouns with Cree nouns (whether animate or inanimate), English pronouns with Cree pronouns, and English particles (of any sort, i.e. adverbs, conjunctions, etc.) with Cree particles, would produce the results that users expect.

A challenge here is how do we determine the part-of-speech for an English search term. We could create an FST for that, but then we'd still need to resolve ambiguous cases. Another challenge is how to do this when there are multiple English key words, which in some cases can be considered a compound with single part of speech (e.g. _**stove pipe**_), but in other cases can be considered a construction with two or more parts of speech (e.g. **_work together_**). In the former, the joint part-of-speech (noun) is based on the p-o-s of the latter component; in the latter the joint p-o-s (verb) is based on the p-o-s of the former component. Simply looking whether the two components occur together might be an initial solution.

Also, why the current solution might not appear to work as well is that crossreferences of the format '_see [ some entry]_' are currently included in the indexing, with unwelcome consequences.

The frequency list can be found in the ALTLab repo in: `./altlab2/crk/corpora/ahenakew_wolfart_fst_and_cg_freq_sorted.txt`

When no corpus lemma frequency is available, one can use inverse lemma length, presuming that shorter lemmas are better than longer one.

**Comment by dwhieb** [comment]
Rather than writing an English FST, what if we got access to either:

1. an English corpus with part-of-speech (POS) tags, which we could then use to determine which POS is most common for each lemma
1. an English dictionary database (or API) that includes information which sense (meaning which part of speech) of a lemma is most common

Coincidentally, I have exactly the kind of data in (1) from my dissertation, but only for 100 lemmas randomly selected from different frequency bins. I'm sure other corpora would have the POS tags we need too though.

**Comment by aarppe** [comment]
We do have at our disposal a general purpose, truly descriptive English analyzer, which has been weighted with the BNC (100 million words), and which provides all possible inflectional and derivational analyses (this is the reason it would be bad for generation). I extracted the original from here: `https://sourceforge.net/projects/hfst/files/resources/morphological-transducers/`

The analyzer `english.hfst `provides all possible readings, whether inflectional or derivational, for its input, so I ran through the English definitions in CW and chose the three top-most analyses, with the following code:

`cat ~/altlab2/crk/dicts/Wolvengrey.tsv| cut -f4 | tail +2 | gawk '{ for(i=1; i<=NF; i++) { gsub("(^[^[:alnum:]]*)|([^[:alnum:]]*$)","",$i); if($i!="" && $i!=" ") print tolower($i); } }' | sort | hfst-optimized-lookup -q Scripts/hfst-english/english.hfstol | gawk 'BEGIN { FS="\n"; RS=""; } { if(index($0,"+?")!=0) err++; else corr++; print $1"\t"$2"\t"$3; } END { print err" vs. "corr" / "NR; }' | sort | uniq -c | sort -nr > ~/altlab2/crk/dicts/Wolvengrey_eng_defs_BNC_analyzed_top3.txt`

The analysis is not exactly ours, but could be easily convertible into that.

Exploring the various techniques superficially, it seemed to me that the vector-semantic one might be able to naturally deal with p-o-s tagging, and it would allow for matches even when a particular English word is not in the English definitions (but close, i.e. a synonym).

If we'd want, we could use the source for `english.hfst `and create a more restricted version for our searches.

**Comment by aarppe** [comment]
This is outdated and no longer relevant due to #1042.
