### ISSUE TITLE
Effectively duplicate entries should be pruned

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/morphodict#700]
There are a number of CW vs. MD entries where definitions from both are shown separately, even though they are for all intents and purposes pretty much the same.

<img width="261" alt="image" src="https://user-images.githubusercontent.com/15003407/111396747-5af96c00-8685-11eb-94c5-c4ff90ceb480.png">

In such a case, only a single definition (from CW, by default) is needed. I'm not sure if this actually concerns only missing coding in the source (currently) XML that can be rectified here.

**Comment by dwhieb** [comment]
The import / merging process for the dictionary database should handle the problem of duplication between CW and MD.
