### ISSUE TITLE
Remove preceding space character(s) when excluding parentheticals

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/morphodict#748]
When excluding parenthetical elements, i.e. `(...)` and `[...]`, remove also the preceding space character(s), so that the insertion of a plural **_-s_** will occur in the correct place. An example with the removable spaces marked with an underscore:

grayling, acrctic grayling_**[Lt. Thymallus arcticus]**; speckled brook trout_**[Lt. Salvelinus fontinalis]**

**Comment by aarppe** [comment]
@dwhieb @andrewdotn I think this becomes moot with the rerepresentation of the definition field into the various components?

**Comment by dwhieb** [comment]
@aarppe Yes this is handled as part of the notes extraction early in the database aggregation process, so this can be closed now.
