### ISSUE TITLE
Simple conjunct forms not recognized

### ISSUE THREAD

**Issue by aaronfay** [UAlbertaALTLab/morphodict#927]
The "conjunct" verb form we commonly refer to falls under what Wolfart (1973p46) refers to as "changed conjunct", eg:

```
ê-kaskihtâyân
```

As learners we still do encounter what Wolfart refers to as the "simple conjunct" in some of the published literature, eg:

```
kaskihtâyân
```
(reference material is kwayask ê-kî-pê-kiskinowâhpahtihicik p18-11 footnote 4)

However this form is not currently recognized by the itwewina: 

![screenshot 2021-07-23 at 21 24 33](https://user-images.githubusercontent.com/1033941/126857217-b7658c54-910d-4150-8c1f-8a65c52b4b6a.png)

**Comment by aarppe** [comment]
Yes, we used to recognize such bare conjuncts, but changed that by design when implementing the interpretation of word-fragments. We might reintroduce that, but strictly speaking they would be non-standard forms, for which itwêwina normally would generate the ê- form.
