### ISSUE TITLE
Tsuut'ina word-forms with macrons do not get analyzed

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/morphodict#970]
When one types in a word-form with macrons, e.g. _ījīn_ or _nádàdāàjísh_ that one can find in the generated paradigms, that word-form does not get an analysis. However, if one removes the macrons, e.g. _ijin_ or _nádàdaàjísh_, that does get analyzed.

Nevertheless, the descriptive FST does recognize and analyze these word-forms, e.g.

```
hfst-optimized-lookup -q srs-analyser-gt-desc.hfstol 

ījīn
ījīn	ījīn+V+I+Ipfv+SbjSg3

ijin
ijin	ījīn+V+I+Ipfv+SbjSg3

nádàdāàjísh
nádàdāàjísh	ījīn+V+I+Ipfv+Rep+SbjPl1+Distr

nadadaajish
nadadaajish	dījí+V+I+Ipfv+Rep+SbjPl1+Distr
nadadaajish	ījīn+V+I+Ipfv+Rep+SbjPl1+Distr

```

**Comment by aarppe** [comment]
Apparently and perhaps interestingly, also running the virtual environment for Gunáhà, the macron characters are not properly recognized, when copy-pasting _ījīn_ to be analyzed:

```
pwd
/Users/arppe/altdev/morphodict

ls src/srseng/
 rc/            srseng-manage*
__init__.py	app		db		resources	site

hfst-optimized-lookup -q src/srseng/resources/fst/analyser-gt-desc.hfstol

D+jD+n
D+jD+n	D+jD+n	+?
```

**Comment by aarppe** [comment]
@nienna73 This now seems to have gotten fixed, so this could be closed, by was there an intentional fix or did this happen as a side-product of other development?

**Comment by aarppe** [comment]
@nienna73 This seems to have resurfaces in the off-line Gunáhà app, cf. the screenshot in Apple Developer:

<img width="298" alt="image" src="https://user-images.githubusercontent.com/15003407/144536723-df3e106e-2048-4bc2-a9e5-4abfabc96004.png">

To cite the feedback there: "When I copy-paste this word exactly as it is presented by Gūnáhà with the macrons, no results are found. I can copy the word from the dictionary header, or the paradigms, but the search never works if the copied word contains any macrons. However, if I type in ‘ijin’ without the macrons, the search succeeds."

**Comment by aarppe** [comment]
@nienna73 This appears to have been fixed again with v2 of the TVPD-based Gunáhà. So it would appear that there was something wrong with either the OS-based lexical DB or FST. In this respect this could be considered closed, but not forgotten when we get back to using an OS-based FST.

**Comment by nienna73** [comment]
I did not directly look into this, so it must have been the updates to the FSTs that fixed this issue.
