### ISSUE TITLE
sources are smushed together

### ISSUE THREAD

**Issue by dwhieb** [UAlbertaALTLab/morphodict#971]
When an entry has multiple sources, they get displayed inline with no spaces separating them, making it hard/impossible to tell that these are distinct sources.

![image](https://user-images.githubusercontent.com/5892997/133340474-8363661f-a756-421c-814e-9e6b92851cba.png)

We should add space or some other indication that each source is distinct.

**Comment by aarppe** [comment]
yes, we should apply some space boundary -> @nienna73, you could look into this.

**Comment by nienna73** [comment]
This doesn't seem to be an issue since updating the dictionary.
